/** Bilingual academic definitions for IELTS vocabulary */
export default {
  alleviate: { en: 'to make pain or difficulty less severe', vi: 'làm giảm bớt, làm dịu đi', exEn: 'Governments must alleviate poverty through targeted welfare programmes.', exVi: 'Chính phủ phải giảm nghèo qua các chương trình phúc lợi mục tiêu.' },
  ambiguous: { en: 'having more than one possible meaning; unclear', vi: 'mơ hồ, không rõ ràng', exEn: 'The survey question was ambiguous and produced unreliable results.', exVi: 'Câu hỏi khảo sát mơ hồ nên cho kết quả không đáng tin.' },
  analogy: { en: 'a comparison between similar things', vi: 'phép so sánh tương tự', exEn: 'She used an analogy between a garden and education to explain growth.', exVi: 'Cô ấy dùng phép so sánh giữa khu vườn và giáo dục để giải thích sự phát triển.' },
  anticipate: { en: 'to expect or prepare for something in advance', vi: 'dự đoán, chuẩn bị trước', exEn: 'Universities anticipate a surge in international applications.', exVi: 'Các trường đại học dự đoán đơn xin từ nước ngoài sẽ tăng mạnh.' },
  arbitrary: { en: 'based on random choice rather than reason', vi: 'tùy tiện, ngẫu nhiên', exEn: 'Arbitrary deadlines can demotivate students.', exVi: 'Hạn chót tùy tiện có thể làm học sinh mất động lực.' },
  assess: { en: 'to evaluate or judge the quality of something', vi: 'đánh giá', exEn: 'Examiners assess writing on four criteria.', exVi: 'Giám khảo đánh giá bài viết theo bốn tiêu chí.' },
  attribute: { en: 'to regard as caused by; a characteristic', vi: 'cho là do; đặc tính', exEn: 'Researchers attribute the decline to climate change.', exVi: 'Nhà nghiên cứu cho rằng sự suy giảm do biến đổi khí hậu.' },
  biodiversity: { en: 'variety of plant and animal life in an area', vi: 'đa dạng sinh học', exEn: 'Protecting biodiversity is essential for ecosystem stability.', exVi: 'Bảo vệ đa dạng sinh học rất cần cho ổn định hệ sinh thái.' },
  coherent: { en: 'logical and consistent; easy to understand', vi: 'mạch lạc, thống nhất', exEn: 'A coherent essay presents ideas in a clear sequence.', exVi: 'Bài luận mạch lạc trình bày ý theo trình tự rõ ràng.' },
  comprehensive: { en: 'complete and including everything necessary', vi: 'toàn diện, đầy đủ', exEn: 'The course offers comprehensive IELTS preparation.', exVi: 'Khóa học cung cấp luyện thi IELTS toàn diện.' },
  conceive: { en: 'to form an idea or plan in the mind', vi: 'hình thành ý tưởng', exEn: 'It is hard to conceive a world without digital communication.', exVi: 'Khó hình dung một thế giới không có giao tiếp số.' },
  consequently: { en: 'as a result; therefore', vi: 'do đó, vì vậy', exEn: 'Funding was cut; consequently, several programmes closed.', exVi: 'Kinh phí bị cắt; do đó, nhiều chương trình đóng cửa.' },
  constitute: { en: 'to form or make up something', vi: 'cấu thành, tạo thành', exEn: 'Women constitute nearly half of the workforce.', exVi: 'Phụ nữ chiếm gần một nửa lực lượng lao động.' },
  contemporary: { en: 'belonging to the present time', vi: 'đương đại, hiện đại', exEn: 'Contemporary art often challenges traditional values.', exVi: 'Nghệ thuật đương đại thường thách thức giá trị truyền thống.' },
  controversial: { en: 'causing public disagreement', vi: 'gây tranh cãi', exEn: 'Genetic editing remains a controversial topic.', exVi: 'Chỉnh sửa gen vẫn là chủ đề gây tranh cãi.' },
  correlate: { en: 'to have a mutual relationship or connection', vi: 'tương quan', exEn: 'Sleep quality correlates strongly with academic performance.', exVi: 'Chất lượng giấc ngủ tương quan mạnh với thành tích học tập.' },
  criteria: { en: 'standards by which something is judged', vi: 'tiêu chí', exEn: 'Candidates are selected based on strict criteria.', exVi: 'Ứng viên được chọn theo tiêu chí nghiêm ngặt.' },
  crucial: { en: 'extremely important or necessary', vi: 'then chốt, cực kỳ quan trọng', exEn: 'Vocabulary range is crucial for a high writing band.', exVi: 'Vốn từ vựng rất quan trọng để đạt band viết cao.' },
  cumulative: { en: 'increasing by successive additions', vi: 'tích lũy', exEn: 'Cumulative practice leads to measurable improvement.', exVi: 'Luyện tập tích lũy mang lại tiến bộ rõ rệt.' },
  deteriorate: { en: 'to become progressively worse', vi: 'xuống cấp, xấu đi', exEn: 'Air quality has deteriorated in major cities.', exVi: 'Chất lượng không khí ở thành phố lớn đã xấu đi.' },
  diminish: { en: 'to reduce or become less', vi: 'giảm bớt, làm suy yếu', exEn: 'Regular review diminishes the risk of forgetting vocabulary.', exVi: 'Ôn tập thường xuyên giảm nguy cơ quên từ vựng.' },
  discriminate: { en: 'to treat differently; to distinguish', vi: 'phân biệt đối xử; phân biệt', exEn: 'Laws prohibit employers from discriminating by gender.', exVi: 'Luật cấm nhà tuyển dụng phân biệt giới tính.' },
  diverse: { en: 'showing great variety', vi: 'đa dạng', exEn: 'A diverse classroom enriches discussion.', exVi: 'Lớp học đa dạng làm phong phú thảo luận.' },
  elaborate: { en: 'detailed and complicated; to expand on', vi: 'tỉ mỉ; trình bày chi tiết', exEn: 'Please elaborate on your main argument with examples.', exVi: 'Hãy trình bày chi tiết luận điểm chính bằng ví dụ.' },
  eliminate: { en: 'to completely remove or get rid of', vi: 'loại bỏ hoàn toàn', exEn: 'Vaccination programmes helped eliminate certain diseases.', exVi: 'Chương trình tiêm chủng giúp loại bỏ một số bệnh.' },
  empirical: { en: 'based on observation or experiment', vi: 'dựa trên thực nghiệm', exEn: 'The theory lacks empirical evidence.', exVi: 'Giả thuyết thiếu bằng chứng thực nghiệm.' },
  enhance: { en: 'to improve the quality or value of', vi: 'nâng cao, cải thiện', exEn: 'Technology can enhance language learning outcomes.', exVi: 'Công nghệ có thể nâng cao kết quả học ngoại ngữ.' },
  equivalent: { en: 'equal in value, amount, or meaning', vi: 'tương đương', exEn: 'Band 7 is equivalent to C1 on the CEFR scale.', exVi: 'Band 7 tương đương C1 trên thang CEFR.' },
  erode: { en: 'to gradually wear away or diminish', vi: 'xói mòn, làm suy yếu dần', exEn: 'Constant criticism can erode students\' confidence.', exVi: 'Chỉ trích liên tục có thể làm suy yếu tự tin học sinh.' },
  exacerbate: { en: 'to make a problem worse', vi: 'làm trầm trọng thêm', exEn: 'Poor planning exacerbated the housing shortage.', exVi: 'Quy hoạch kém làm trầm trọng thêm thiếu nhà ở.' },
  facilitate: { en: 'to make an action easier', vi: 'tạo điều kiện thuận lợi', exEn: 'Online tools facilitate collaborative study.', exVi: 'Công cụ trực tuyến tạo điều kiện học nhóm.' },
  fluctuate: { en: 'to rise and fall irregularly', vi: 'dao động', exEn: 'Exchange rates fluctuate daily.', exVi: 'Tỷ giá dao động hàng ngày.' },
  fundamental: { en: 'forming a necessary base; essential', vi: 'cơ bản, nền tảng', exEn: 'Grammar is fundamental to clear communication.', exVi: 'Ngữ pháp là nền tảng của giao tiếp rõ ràng.' },
  hypothesis: { en: 'a proposed explanation to be tested', vi: 'giả thuyết', exEn: 'The study tests the hypothesis that sleep affects memory.', exVi: 'Nghiên cứu kiểm chứng giả thuyết giấc ngủ ảnh hưởng trí nhớ.' },
  implement: { en: 'to put a plan into action', vi: 'triển khai, thực hiện', exEn: 'Schools will implement the new curriculum next year.', exVi: 'Trường học sẽ triển khai chương trình mới năm sau.' },
  implication: { en: 'a possible effect or consequence', vi: 'hàm ý, hệ quả', exEn: 'The policy has serious implications for rural communities.', exVi: 'Chính sách có hệ quả nghiêm trọng với cộng đồng nông thôn.' },
  incentive: { en: 'something that motivates action', vi: 'động lực, khuyến khích', exEn: 'Scholarships provide a strong incentive to study abroad.', exVi: 'Học bổng tạo động lực mạnh để du học.' },
  inevitable: { en: 'certain to happen; unavoidable', vi: 'không thể tránh khỏi', exEn: 'Technological change is inevitable in modern society.', exVi: 'Thay đổi công nghệ là không thể tránh trong xã hội hiện đại.' },
  infrastructure: { en: 'basic physical systems of a country', vi: 'cơ sở hạ tầng', exEn: 'Investment in infrastructure boosts economic growth.', exVi: 'Đầu tư hạ tầng thúc đẩy tăng trưởng kinh tế.' },
  inherent: { en: 'existing as a natural part of something', vi: 'vốn có, cố hữu', exEn: 'There are inherent risks in any medical procedure.', exVi: 'Mọi thủ thuật y khoa đều có rủi ro vốn có.' },
  innovative: { en: 'featuring new methods or ideas', vi: 'đổi mới, sáng tạo', exEn: 'Innovative teaching methods engage students more effectively.', exVi: 'Phương pháp giảng dạy đổi mới thu hút học sinh hiệu quả hơn.' },
  integrate: { en: 'to combine into a unified whole', vi: 'tích hợp', exEn: 'Schools integrate technology into daily lessons.', exVi: 'Trường học tích hợp công nghệ vào bài học hàng ngày.' },
  intervene: { en: 'to become involved to alter a situation', vi: 'can thiệp', exEn: 'Governments may intervene when markets fail.', exVi: 'Chính phủ có thể can thiệp khi thị trường thất bại.' },
  legislation: { en: 'laws considered collectively', vi: 'pháp luật, luật pháp', exEn: 'New legislation protects consumer data online.', exVi: 'Luật mới bảo vệ dữ liệu người tiêu dùng trực tuyến.' },
  mitigate: { en: 'to make something less severe', vi: 'giảm nhẹ, làm dịu', exEn: 'Trees mitigate the effects of urban heat.', exVi: 'Cây xanh giảm nhẹ tác động nhiệt đô thị.' },
  notion: { en: 'a general idea or belief', vi: 'quan niệm, ý niệm', exEn: 'The notion of lifelong learning is widely accepted.', exVi: 'Quan niệm học suốt đời được chấp nhận rộng rãi.' },
  obsolete: { en: 'no longer in use; outdated', vi: 'lỗi thời', exEn: 'Some skills become obsolete as technology advances.', exVi: 'Một số kỹ năng lỗi thời khi công nghệ tiến bộ.' },
  paradigm: { en: 'a typical pattern or model', vi: 'mô hình, khuôn mẫu', exEn: 'Remote work shifted the paradigm of office culture.', exVi: 'Làm việc từ xa thay đổi mô hình văn hóa văn phòng.' },
  phenomenon: { en: 'a fact or event that is observed', vi: 'hiện tượng', exEn: 'Urbanisation is a global phenomenon.', exVi: 'Đô thị hóa là hiện tượng toàn cầu.' },
  sustainability: { en: 'ability to be maintained without depleting resources', vi: 'bền vững', exEn: 'Sustainability requires balancing growth and conservation.', exVi: 'Bền vững đòi hỏi cân bằng tăng trưởng và bảo tồn.' },
  proliferation: { en: 'rapid increase in numbers', vi: 'sự gia tăng nhanh', exEn: 'The proliferation of smartphones changed communication.', exVi: 'Sự bùng nổ smartphone thay đổi giao tiếp.' },
  detrimental: { en: 'causing harm or damage', vi: 'có hại', exEn: 'Excessive screen time can be detrimental to sleep.', exVi: 'Dùng màn hình quá nhiều có hại cho giấc ngủ.' },
  subsequently: { en: 'afterwards; following in time', vi: 'sau đó', exEn: 'He graduated and subsequently pursued a master\'s degree.', exVi: 'Anh ấy tốt nghiệp và sau đó học thạc sĩ.' },
  predominantly: { en: 'mainly; for the most part', vi: 'chủ yếu', exEn: 'The audience was predominantly young professionals.', exVi: 'Khán giả chủ yếu là chuyên gia trẻ.' },
  unprecedented: { en: 'never done or known before', vi: 'chưa từng có', exEn: 'The pandemic caused unprecedented disruption to education.', exVi: 'Đại dịch gây gián đoạn giáo dục chưa từng có.' },
  paramount: { en: 'more important than anything else', vi: 'tối quan trọng', exEn: 'Student safety is of paramount importance.', exVi: 'An toàn học sinh là tối quan trọng.' },
  quintessential: { en: 'representing the most perfect example', vi: 'tiêu biểu nhất', exEn: 'She is the quintessential dedicated teacher.', exVi: 'Cô ấy là hình mẫu tiêu biểu của giáo viên tận tâm.' },
  ramification: { en: 'a complex consequence of an action', vi: 'hệ quả phức tạp', exEn: 'Policy changes have far-reaching ramifications.', exVi: 'Thay đổi chính sách có hệ quả sâu rộng.' },
  repercussion: { en: 'an unintended consequence', vi: 'hậu quả', exEn: 'Economic sanctions may have global repercussions.', exVi: 'Trừng phạt kinh tế có thể gây hậu quả toàn cầu.' },
  scrutinize: { en: 'to examine closely and critically', vi: 'xem xét kỹ lưỡng', exEn: 'Auditors scrutinize financial records each quarter.', exVi: 'Kiểm toán viên xem xét kỹ sổ sách mỗi quý.' },
  substantiate: { en: 'to provide evidence to support', vi: 'chứng minh, bổ sung bằng chứng', exEn: 'Claims must be substantiated with reliable data.', exVi: 'Tuyên bố phải được chứng minh bằng dữ liệu đáng tin.' },
  surpass: { en: 'to exceed or go beyond', vi: 'vượt qua', exEn: 'Her score surpassed the national average.', exVi: 'Điểm của cô ấy vượt mức trung bình quốc gia.' },
  tangible: { en: 'clear and definite; perceptible', vi: 'hữu hình, rõ ràng', exEn: 'Students need tangible feedback on their writing.', exVi: 'Học sinh cần phản hồi rõ ràng về bài viết.' },
  tenacious: { en: 'persistent and determined', vi: 'kiên trì, bền bỉ', exEn: 'Tenacious learners eventually reach their target band.', exVi: 'Người học kiên trì cuối cùng đạt band mục tiêu.' },
  transient: { en: 'lasting only for a short time', vi: 'tạm thời, thoáng qua', exEn: 'Economic booms are often transient.', exVi: 'Bùng nổ kinh tế thường chỉ tạm thời.' },
  undermine: { en: 'to weaken gradually', vi: 'làm suy yếu', exEn: 'Misinformation can undermine public trust.', exVi: 'Thông tin sai lệch có thể làm suy yếu niềm tin công chúng.' },
  validate: { en: 'to confirm the accuracy of', vi: 'xác nhận, chứng thực', exEn: 'Further studies are needed to validate the findings.', exVi: 'Cần thêm nghiên cứu để xác nhận kết quả.' },
  versatile: { en: 'able to adapt to many functions', vi: 'linh hoạt, đa năng', exEn: 'English is a versatile tool for global careers.', exVi: 'Tiếng Anh là công cụ linh hoạt cho sự nghiệp toàn cầu.' },
  viable: { en: 'capable of working successfully', vi: 'khả thi', exEn: 'Solar power is now a viable energy source.', exVi: 'Điện mặt trời giờ là nguồn năng lượng khả thi.' },
  volatile: { en: 'likely to change suddenly', vi: 'biến động mạnh', exEn: 'Oil prices remain volatile.', exVi: 'Giá dầu vẫn biến động mạnh.' },
  widespread: { en: 'found or happening over a large area', vi: 'phổ biến rộng rãi', exEn: 'There is widespread support for renewable energy.', exVi: 'Năng lượng tái tạo được ủng hộ rộng rãi.' },
  advocate: { en: 'to publicly support; a supporter', vi: 'ủng hộ; người ủng hộ', exEn: 'Many educators advocate bilingual instruction.', exVi: 'Nhiều nhà giáo dục ủng hộ giảng dạy song ngữ.' },
  allocate: { en: 'to distribute for a specific purpose', vi: 'phân bổ', exEn: 'The budget allocates funds to rural schools.', exVi: 'Ngân sách phân bổ kinh phí cho trường nông thôn.' },
  anomaly: { en: 'something that deviates from the norm', vi: 'bất thường, dị thường', exEn: 'The result was an anomaly that required further study.', exVi: 'Kết quả là bất thường cần nghiên cứu thêm.' },
  autonomous: { en: 'self-governing; independent', vi: 'tự trị, tự chủ', exEn: 'Autonomous vehicles may transform urban transport.', exVi: 'Xe tự lái có thể thay đổi giao thông đô thị.' },
  benchmark: { en: 'a standard for comparison', vi: 'chuẩn mực, tiêu chuẩn', exEn: 'Band 7 serves as a benchmark for university admission.', exVi: 'Band 7 là chuẩn mực tuyển sinh đại học.' },
  bolster: { en: 'to support or strengthen', vi: 'củng cố, tăng cường', exEn: 'Practice tests bolster exam confidence.', exVi: 'Thi thử củng cố tự tin trước kỳ thi.' },
  burgeoning: { en: 'growing or developing rapidly', vi: 'đang phát triển nhanh', exEn: 'The burgeoning ed-tech sector attracts investment.', exVi: 'Ngành ed-tech đang bùng nổ thu hút đầu tư.' },
  catalyst: { en: 'something that speeds up change', vi: 'chất xúc tác, yếu tố thúc đẩy', exEn: 'IELTS can be a catalyst for international opportunities.', exVi: 'IELTS có thể là động lực mở cơ hội quốc tế.' },
  circumvent: { en: 'to find a way around an obstacle', vi: 'lách luật, tránh né', exEn: 'Students should not circumvent academic integrity rules.', exVi: 'Học sinh không nên lách quy tắc trung thực học thuật.' },
  coalesce: { en: 'to come together to form one mass', vi: 'hợp nhất, kết hợp', exEn: 'Diverse ideas coalesce into a coherent argument.', exVi: 'Ý tưởng đa dạng hợp nhất thành luận điểm mạch lạc.' },
  commensurate: { en: 'corresponding in size or degree', vi: 'tương xứng', exEn: 'Salary should be commensurate with experience.', exVi: 'Lương nên tương xứng với kinh nghiệm.' },
  compelling: { en: 'evoking interest; convincing', vi: 'thuyết phục, hấp dẫn', exEn: 'She presented a compelling case for reform.', exVi: 'Cô ấy trình bày lập luận thuyết phục về cải cách.' },
  conducive: { en: 'making a situation likely to happen', vi: 'có lợi cho, tạo điều kiện', exEn: 'A quiet library is conducive to focused study.', exVi: 'Thư viện yên tĩnh tạo điều kiện học tập tập trung.' },
  conjecture: { en: 'an opinion without sufficient evidence', vi: 'phỏng đoán', exEn: 'Without data, the claim remains mere conjecture.', exVi: 'Không có dữ liệu, tuyên bố chỉ là phỏng đoán.' },
  consolidate: { en: 'to strengthen or combine', vi: 'củng cố, hợp nhất', exEn: 'Review sessions help consolidate grammar knowledge.', exVi: 'Buổi ôn tập giúp củng cố kiến thức ngữ pháp.' },
  converge: { en: 'to come together from different directions', vi: 'hội tụ', exEn: 'Global trends converge on digital education.', exVi: 'Xu hướng toàn cầu hội tụ về giáo dục số.' },
  corroborate: { en: 'to confirm with supporting evidence', vi: 'xác nhận, chứng thực', exEn: 'Two studies corroborate the same conclusion.', exVi: 'Hai nghiên cứu xác nhận cùng kết luận.' },
  culminate: { en: 'to reach a climax or conclusion', vi: 'đạt đỉnh điểm, kết thúc', exEn: 'Years of practice culminated in her Band 8 score.', exVi: 'Nhiều năm luyện tập đạt đỉnh với Band 8.' },
  cumbersome: { en: 'large and difficult to handle', vi: 'cồng kềnh, phiền phức', exEn: 'Cumbersome procedures delay project approval.', exVi: 'Thủ tục cồng kềnh trì hoãn phê duyệt dự án.' },
  debilitate: { en: 'to make weak or infirm', vi: 'làm suy yếu', exEn: 'Chronic stress can debilitate immune function.', exVi: 'Căng thẳng mãn tính làm suy yếu miễn dịch.' },
  decipher: { en: 'to convert into understandable form', vi: 'giải mã, đọc hiểu', exEn: 'Students must decipher complex academic texts.', exVi: 'Học sinh phải đọc hiểu văn bản học thuật phức tạp.' },
  deplete: { en: 'to use up resources', vi: 'cạn kiệt', exEn: 'Overfishing depletes marine stocks.', exVi: 'Đánh bắt quá mức cạn kiệt nguồn cá biển.' },
  depreciate: { en: 'to decrease in value', vi: 'mất giá', exEn: 'Currency may depreciate during economic crises.', exVi: 'Tiền tệ có thể mất giá trong khủng hoảng.' },
  deterrent: { en: 'something that discourages action', vi: 'rào cản, yếu tố răn đe', exEn: 'High fees act as a deterrent to some applicants.', exVi: 'Học phí cao là rào cản với một số ứng viên.' },
  discrepancy: { en: 'a lack of agreement between facts', vi: 'sự khác biệt, mâu thuẫn', exEn: 'There is a discrepancy between the two reports.', exVi: 'Hai báo cáo có sự khác biệt.' },
  disseminate: { en: 'to spread widely', vi: 'phổ biến, truyền bá', exEn: 'Universities disseminate research through journals.', exVi: 'Đại học phổ biến nghiên cứu qua tạp chí.' },
  diverge: { en: 'to separate and go in different directions', vi: 'phân kỳ, đi theo hướng khác', exEn: 'Opinions diverge on the best teaching method.', exVi: 'Ý kiến phân kỳ về phương pháp giảng dạy tốt nhất.' },
  elicit: { en: 'to draw out a response', vi: 'gợi ra, khơi gợi', exEn: 'Good questions elicit thoughtful answers.', exVi: 'Câu hỏi hay gợi ra câu trả lời sâu sắc.' },
  emulate: { en: 'to imitate with effort to equal', vi: 'noi gương, bắt chước', exEn: 'Learners emulate native speakers\' intonation.', exVi: 'Người học bắt chước ngữ điệu người bản ngữ.' },
  endeavor: { en: 'a serious effort; to try hard', vi: 'nỗ lực', exEn: 'Mastering IELTS is a worthwhile endeavor.', exVi: 'Chinh phục IELTS là nỗ lực đáng giá.' },
  engender: { en: 'to cause a feeling to exist', vi: 'gây ra, tạo ra', exEn: 'Fair grading engenders trust in the system.', exVi: 'Chấm điểm công bằng tạo niềm tin vào hệ thống.' },
  envisage: { en: 'to imagine as a future possibility', vi: 'hình dung', exEn: 'It is hard to envisage life without the internet.', exVi: 'Khó hình dung cuộc sống không có internet.' },
  epitomize: { en: 'to be a perfect example of', vi: 'là hình mẫu tiêu biểu', exEn: 'The essay epitomizes clear academic writing.', exVi: 'Bài luận là hình mẫu viết học thuật rõ ràng.' },
  escalate: { en: 'to increase rapidly in intensity', vi: 'leo thang', exEn: 'Tensions escalated after the announcement.', exVi: 'Căng thẳng leo thang sau thông báo.' },
  exemplify: { en: 'to be a typical example of', vi: 'minh họa, là ví dụ điển hình', exEn: 'This case exemplifies effective public policy.', exVi: 'Trường hợp này minh họa chính sách công hiệu quả.' },
  expedite: { en: 'to make an action happen sooner', vi: 'đẩy nhanh', exEn: 'Digital forms expedite the application process.', exVi: 'Biểu mẫu số đẩy nhanh quy trình nộp đơn.' },
  extrapolate: { en: 'to extend known data to predict', vi: 'ngoại suy', exEn: 'Scientists extrapolate trends from sample data.', exVi: 'Nhà khoa học ngoại suy xu hướng từ mẫu dữ liệu.' },
  feasible: { en: 'possible and practical to do', vi: 'khả thi', exEn: 'Studying two hours daily is feasible for most students.', exVi: 'Học hai giờ mỗi ngày khả thi với đa số học sinh.' },
  flourish: { en: 'to grow or develop successfully', vi: 'phát triển thịnh vượng', exEn: 'Creative industries flourish in major cities.', exVi: 'Ngành sáng tạo phát triển ở thành phố lớn.' },
  formidable: { en: 'inspiring fear or respect through difficulty', vi: 'đáng gờm, khó đối phó', exEn: 'IELTS Writing Task 2 is a formidable challenge.', exVi: 'Writing Task 2 IELTS là thử thách đáng gờm.' },
  fortify: { en: 'to strengthen physically or mentally', vi: 'củng cố, tăng cường', exEn: 'Mock tests fortify exam readiness.', exVi: 'Thi thử củng cố sự sẵn sàng thi.' },
  foster: { en: 'to encourage development', vi: 'nuôi dưỡng, thúc đẩy', exEn: 'Teachers foster critical thinking in class.', exVi: 'Giáo viên nuôi dưỡng tư duy phản biện trong lớp.' },
  galvanize: { en: 'to shock into action', vi: 'thúc đẩy mạnh mẽ', exEn: 'The speech galvanized students to volunteer.', exVi: 'Bài phát biểu thúc đẩy sinh viên tình nguyện.' },
  gauge: { en: 'to measure or judge', vi: 'đo lường, đánh giá', exEn: 'Mock tests gauge your current band level.', exVi: 'Thi thử đo lường band hiện tại của bạn.' },
  hamper: { en: 'to hinder or impede', vi: 'cản trở', exEn: 'Noise can hamper concentration during study.', exVi: 'Tiếng ồn cản trở sự tập trung khi học.' },
  hinder: { en: 'to create difficulties', vi: 'cản trở, gây khó khăn', exEn: 'Poor internet hinders online learning.', exVi: 'Mạng kém cản trở học trực tuyến.' },
  homogeneous: { en: 'of the same kind; uniform', vi: 'đồng nhất', exEn: 'A homogeneous group may lack diverse perspectives.', exVi: 'Nhóm đồng nhất có thể thiếu góc nhìn đa dạng.' },
  impede: { en: 'to delay or block progress', vi: 'cản trở', exEn: 'Bureaucracy can impede innovation.', exVi: 'Quan liêu có thể cản trở đổi mới.' },
  imperative: { en: 'of vital importance; urgent', vi: 'cấp bách, bắt buộc', exEn: 'It is imperative to manage time during the exam.', exVi: 'Quản lý thời gian trong kỳ thi là bắt buộc.' },
  inadvertent: { en: 'unintentional', vi: 'vô tình, không cố ý', exEn: 'Inadvertent errors still affect the score.', exVi: 'Lỗi vô tình vẫn ảnh hưởng điểm.' },
  incumbent: { en: 'currently holding a position', vi: 'đương nhiệm', exEn: 'The incumbent director announced reforms.', exVi: 'Giám đốc đương nhiệm công bố cải cách.' },
  indigenous: { en: 'native to a particular region', vi: 'bản địa', exEn: 'Indigenous knowledge preserves biodiversity.', exVi: 'Tri thức bản địa bảo tồn đa dạng sinh học.' },
  indispensable: { en: 'absolutely necessary', vi: 'không thể thiếu', exEn: 'Practice is indispensable for IELTS success.', exVi: 'Luyện tập không thể thiếu để đạt IELTS.' },
  infer: { en: 'to deduce from evidence', vi: 'suy luận', exEn: 'Readers infer meaning from context clues.', exVi: 'Người đọc suy luận nghĩa từ ngữ cảnh.' },
  infringe: { en: 'to violate a law or right', vi: 'vi phạm', exEn: 'Copying essays infringes academic integrity.', exVi: 'Chép bài vi phạm trung thực học thuật.' },
  innate: { en: 'inborn; natural', vi: 'bẩm sinh', exEn: 'Language aptitude has both innate and learned aspects.', exVi: 'Năng khiếu ngôn ngữ có yếu tố bẩm sinh và học được.' },
  insightful: { en: 'showing deep understanding', vi: 'sâu sắc', exEn: 'Her essay offered insightful analysis.', exVi: 'Bài luận của cô ấy phân tích sâu sắc.' },
  instigate: { en: 'to bring about or initiate', vi: 'khởi xướng, kích động', exEn: 'Protests instigated policy debate.', exVi: 'Biểu tình khởi xướng tranh luận chính sách.' },
  integral: { en: 'essential; forming a whole', vi: 'không thể thiếu; tích hợp', exEn: 'Feedback is integral to improvement.', exVi: 'Phản hồi là phần không thể thiếu để tiến bộ.' },
  intermittent: { en: 'occurring at irregular intervals', vi: 'gián đoạn, không liên tục', exEn: 'Intermittent rain disrupted the outdoor event.', exVi: 'Mưa gián đoạn làm gián đoạn sự kiện ngoài trời.' },
  intricate: { en: 'very complex and detailed', vi: 'phức tạp tinh vi', exEn: 'IELTS reading passages can be intricate.', exVi: 'Đoạn đọc IELTS có thể rất phức tạp.' },
  intrinsic: { en: 'belonging naturally; essential', vi: 'vốn có, bản chất', exEn: 'Curiosity is intrinsic to effective learning.', exVi: 'Tò mò là bản chất của học tập hiệu quả.' },
  juxtapose: { en: 'to place side by side for contrast', vi: 'đặt cạnh để so sánh', exEn: 'The author juxtaposes urban and rural life.', exVi: 'Tác giả đặt cạnh đời sống thành thị và nông thôn.' },
  lucrative: { en: 'producing great profit', vi: 'sinh lời cao', exEn: 'Tech careers can be highly lucrative.', exVi: 'Nghề công nghệ có thể sinh lời cao.' },
  magnitude: { en: 'great size or importance', vi: 'quy mô, tầm quan trọng', exEn: 'We underestimated the magnitude of the challenge.', exVi: 'Chúng ta đánh giá thấp quy mô thử thách.' },
  manifest: { en: 'to display clearly; obvious', vi: 'biểu hiện rõ; rõ ràng', exEn: 'Stress can manifest as poor concentration.', exVi: 'Căng thẳng biểu hiện qua mất tập trung.' },
  marginal: { en: 'relating to the edge; slight', vi: 'ở rìa; nhỏ', exEn: 'Marginal improvements still raise the band score.', exVi: 'Cải thiện nhỏ vẫn nâng band.' },
  meticulous: { en: 'showing great attention to detail', vi: 'tỉ mỉ', exEn: 'Meticulous proofreading prevents errors.', exVi: 'Đọc lại tỉ mỉ tránh lỗi.' },
  monolithic: { en: 'massive and uniform', vi: 'khối thống nhất, đồng nhất', exEn: 'Education systems are rarely monolithic.', exVi: 'Hệ giáo dục hiếm khi đồng nhất hoàn toàn.' },
  multifaceted: { en: 'having many aspects', vi: 'đa chiều', exEn: 'Climate change is a multifaceted problem.', exVi: 'Biến đổi khí hậu là vấn đề đa chiều.' },
  nascent: { en: 'just beginning to develop', vi: 'mới hình thành', exEn: 'Nascent industries need government support.', exVi: 'Ngành mới hình thành cần hỗ trợ chính phủ.' },
  negligible: { en: 'so small as to be unimportant', vi: 'không đáng kể', exEn: 'The price difference is negligible.', exVi: 'Chênh lệch giá không đáng kể.' },
  nuance: { en: 'a subtle difference in meaning', vi: 'sắc thái', exEn: 'Band 8 writers capture nuance in vocabulary.', exVi: 'Người viết Band 8 nắm sắc thái từ vựng.' },
  oblivious: { en: 'unaware of what is happening', vi: 'không nhận ra', exEn: 'He was oblivious to the deadline.', exVi: 'Anh ấy không nhận ra hạn chót.' },
  omnipresent: { en: 'present everywhere', vi: 'hiện diện khắp nơi', exEn: 'Smartphones are omnipresent in modern life.', exVi: 'Smartphone hiện diện khắp nơi trong đời sống hiện đại.' },
  onerous: { en: 'involving great effort; burdensome', vi: 'nặng nề, khó khăn', exEn: 'Onerous regulations discourage small businesses.', exVi: 'Quy định nặng nề làm nhỏ lệ doanh nghiệp.' },
  optimal: { en: 'best or most favourable', vi: 'tối ưu', exEn: 'Morning study may be optimal for some learners.', exVi: 'Học buổi sáng có thể tối ưu với một số người.' },
  ornate: { en: 'elaborately decorated', vi: 'trang trí cầu kỳ', exEn: 'Ornate language can obscure meaning in essays.', exVi: 'Văn phong cầu kỳ có thể che khuất ý trong bài luận.' },
  ostensible: { en: 'appearing true but possibly not', vi: 'bề ngoài, có vẻ', exEn: 'The ostensible reason masked deeper issues.', exVi: 'Lý do bề ngoài che giấu vấn đề sâu xa.' },
  paradox: { en: 'a seemingly contradictory statement', vi: 'nghịch lý', exEn: 'It is a paradox that more choice can reduce satisfaction.', exVi: 'Nghịch lý là nhiều lựa chọn có thể giảm hài lòng.' },
  pervasive: { en: 'spreading widely throughout', vi: 'lan tỏa khắp nơi', exEn: 'Social media has a pervasive influence on youth.', exVi: 'Mạng xã hội ảnh hưởng lan tỏa đến thanh niên.' },
  plausible: { en: 'seeming reasonable or probable', vi: 'hợp lý, có vẻ đúng', exEn: 'The explanation sounds plausible but lacks evidence.', exVi: 'Giải thích nghe hợp lý nhưng thiếu bằng chứng.' },
  pragmatic: { en: 'dealing with things practically', vi: 'thực tiễn', exEn: 'A pragmatic approach focuses on achievable goals.', exVi: 'Cách tiếp cận thực tiễn tập trung mục tiêu khả thi.' },
  precarious: { en: 'not securely held; uncertain', vi: 'bấp bênh, không chắc chắn', exEn: 'Freelancers often face precarious income.', exVi: 'Freelancer thường đối mặt thu nhập bấp bênh.' },
  preclude: { en: 'to prevent from happening', vi: 'ngăn cản', exEn: 'Low scores preclude admission to top programmes.', exVi: 'Điểm thấp ngăn tuyển vào chương trình hàng đầu.' },
  predilection: { en: 'a preference for something', vi: 'thiên hướng, sở thích', exEn: 'She has a predilection for argumentative essays.', exVi: 'Cô ấy có thiên hướng viết luận tranh luận.' },
  preliminary: { en: 'coming before the main part', vi: 'sơ bộ, ban đầu', exEn: 'Preliminary results suggest further research is needed.', exVi: 'Kết quả sơ bộ cho thấy cần nghiên cứu thêm.' },
  presume: { en: 'to suppose without proof', vi: 'cho rằng, giả định', exEn: 'Do not presume the answer without reading fully.', exVi: 'Đừng giả định đáp án khi chưa đọc kỹ.' },
  profound: { en: 'very great or intense; deep', vi: 'sâu sắc', exEn: 'Travel had a profound impact on her worldview.', exVi: 'Du lịch tác động sâu sắc đến thế giới quan cô ấy.' },
  prolific: { en: 'producing much output', vi: 'có năng suất cao', exEn: 'He is a prolific writer of IELTS materials.', exVi: 'Ông ấy viết tài liệu IELTS rất nhiều.' },
  prominent: { en: 'important; well-known', vi: 'nổi bật', exEn: 'She is a prominent figure in education reform.', exVi: 'Cô ấy là nhân vật nổi bật trong cải cách giáo dục.' },
  prone: { en: 'likely to suffer from', vi: 'dễ bị, có khuynh hướng', exEn: 'Students are prone to procrastination before exams.', exVi: 'Học sinh dễ trì hoãn trước kỳ thi.' },
  proponent: { en: 'a person who advocates for', vi: 'người ủng hộ', exEn: 'Proponents of online learning cite flexibility.', exVi: 'Người ủng hộ học trực tuyến nhấn mạnh tính linh hoạt.' },
  prosperous: { en: 'successful and thriving', vi: 'thịnh vượng', exEn: 'Education correlates with prosperous communities.', exVi: 'Giáo dục gắn với cộng đồng thịnh vượng.' },
  prudent: { en: 'acting with care and thought', vi: 'thận trọng', exEn: 'It is prudent to simulate exam conditions.', exVi: 'Mô phỏng điều kiện thi là thận trọng.' },
  rampant: { en: 'uncontrolled; widespread', vi: 'tràn lan', exEn: 'Misinformation is rampant on social platforms.', exVi: 'Thông tin sai tràn lan trên mạng xã hội.' },
  reciprocal: { en: 'given and received in return', vi: 'có đi có lại', exEn: 'Learning benefits from reciprocal feedback.', exVi: 'Học tập hưởng lợi từ phản hồi qua lại.' },
  reconcile: { en: 'to restore friendly relations; to make consistent', vi: 'hòa giải; hài hòa', exEn: 'Policy must reconcile growth and sustainability.', exVi: 'Chính sách phải hài hòa tăng trưởng và bền vững.' },
  redundant: { en: 'no longer needed; repetitive', vi: 'thừa, lặp lại', exEn: 'Avoid redundant phrases in academic writing.', exVi: 'Tránh cụm từ thừa trong văn viết học thuật.' },
  refute: { en: 'to prove a statement wrong', vi: 'bác bỏ', exEn: 'New data refute the earlier hypothesis.', exVi: 'Dữ liệu mới bác bỏ giả thuyết trước.' },
  reiterate: { en: 'to say again for emphasis', vi: 'nhắc lại', exEn: 'The examiner reiterated the time limit.', exVi: 'Giám khảo nhắc lại giới hạn thời gian.' },
  relinquish: { en: 'to give up voluntarily', vi: 'từ bỏ', exEn: 'He refused to relinquish his leadership role.', exVi: 'Anh ấy từ chối từ bỏ vai trò lãnh đạo.' },
  reminiscent: { en: 'tending to remind of something', vi: 'gợi nhớ', exEn: 'The melody is reminiscent of traditional folk songs.', exVi: 'Giai điệu gợi nhớ dân ca truyền thống.' },
  replicate: { en: 'to make an exact copy; repeat', vi: 'nhân bản, lặp lại', exEn: 'Researchers replicate experiments to verify results.', exVi: 'Nhà khoa học lặp lại thí nghiệm để xác minh.' },
  resilient: { en: 'able to recover quickly', vi: 'kiên cường, phục hồi nhanh', exEn: 'Resilient learners bounce back after low scores.', exVi: 'Người học kiên cường vượt qua điểm thấp.' },
  restrain: { en: 'to prevent from doing something', vi: 'kiềm chế, hạn chế', exEn: 'Students must restrain impulse answers in reading.', exVi: 'Học sinh phải kiềm chế trả lời vội khi đọc.' },
  retrospect: { en: 'looking back on past events', vi: 'nhìn lại quá khứ', exEn: 'In retrospect, daily practice was the key.', exVi: 'Nhìn lại, luyện tập hàng ngày là chìa khóa.' },
  rhetoric: { en: 'the art of persuasive speaking', vi: 'hùng biện, tu từ', exEn: 'Political rhetoric often oversimplifies complex issues.', exVi: 'Tu từ chính trị thường đơn giản hóa vấn đề phức tạp.' },
  rudimentary: { en: 'basic; not fully developed', vi: 'sơ đẳng, cơ bản', exEn: 'He has only rudimentary knowledge of grammar.', exVi: 'Anh ấy chỉ có kiến thức ngữ pháp cơ bản.' },
  salient: { en: 'most noticeable or important', vi: 'nổi bật, quan trọng nhất', exEn: 'Identify the salient features of the chart.', exVi: 'Xác định đặc điểm nổi bật của biểu đồ.' },
  scrutiny: { en: 'critical observation or examination', vi: 'sự xem xét kỹ', exEn: 'Funding proposals face public scrutiny.', exVi: 'Đề xuất kinh phí chịu sự xem xét công chúng.' },
  secular: { en: 'not connected with religion', vi: 'thế tục', exEn: 'Many countries provide secular education.', exVi: 'Nhiều quốc gia cung cấp giáo dục thế tục.' },
  sedentary: { en: 'involving much sitting; inactive', vi: 'ít vận động', exEn: 'Sedentary lifestyles increase health risks.', exVi: 'Lối sống ít vận động tăng rủi ro sức khỏe.' },
  serendipity: { en: 'finding something good by chance', vi: 'tình cờ may mắn', exEn: 'Serendipity led her to discover a useful study method.', exVi: 'Tình cờ giúp cô ấy tìm ra phương pháp học hữu ích.' },
  skeptical: { en: 'having doubts; not easily convinced', vi: 'hoài nghi', exEn: 'Experts remain skeptical about the new claim.', exVi: 'Chuyên gia vẫn hoài nghi về tuyên bố mới.' },
  sovereign: { en: 'having supreme power; independent', vi: 'chủ quyền', exEn: 'Each nation retains sovereign control over education.', exVi: 'Mỗi quốc gia giữ quyền chủ quyền giáo dục.' },
  sporadic: { en: 'occurring irregularly', vi: 'rời rạc, không đều', exEn: 'Sporadic study yields inconsistent results.', exVi: 'Học rời rạc cho kết quả không ổn định.' },
  stagnant: { en: 'showing no activity or development', vi: 'trì trệ', exEn: 'Stagnant wages concern young workers.', exVi: 'Lương trì trệ khiến lao động trẻ lo ngại.' },
  stipulate: { en: 'to demand as a condition', vi: 'quy định', exEn: 'Universities stipulate minimum IELTS requirements.', exVi: 'Đại học quy định yêu cầu IELTS tối thiểu.' },
  subordinate: { en: 'lower in rank; less important', vi: 'cấp dưới; phụ thuộc', exEn: 'Subordinate clauses add complexity to sentences.', exVi: 'Mệnh đề phụ thuộc làm câu phức tạp hơn.' },
  substantial: { en: 'of considerable importance or size', vi: 'đáng kể', exEn: 'She made substantial progress in two months.', exVi: 'Cô ấy tiến bộ đáng kể trong hai tháng.' },
  succinct: { en: 'briefly and clearly expressed', vi: 'súc tích', exEn: 'A succinct introduction sets a strong tone.', exVi: 'Mở bài súc tích tạo ấn tượng tốt.' },
  supersede: { en: 'to replace something older', vi: 'thay thế', exEn: 'Digital records supersede paper archives.', exVi: 'Hồ sơ số thay thế kho giấy.' },
  susceptible: { en: 'likely to be influenced or harmed', vi: 'dễ bị ảnh hưởng', exEn: 'Children are susceptible to advertising.', exVi: 'Trẻ em dễ bị quảng cáo ảnh hưởng.' },
  synthesis: { en: 'combining ideas into a whole', vi: 'tổng hợp', exEn: 'Task 2 requires synthesis of multiple viewpoints.', exVi: 'Task 2 đòi hỏi tổng hợp nhiều quan điểm.' },
  tacit: { en: 'understood without being stated', vi: 'ngầm hiểu', exEn: 'There was tacit agreement to share notes.', exVi: 'Có sự đồng thuận ngầm chia sẻ ghi chú.' },
  tedious: { en: 'too long, slow, or boring', vi: 'nhàm chán, tẻ nhạt', exEn: 'Proofreading can feel tedious but is essential.', exVi: 'Đọc lại có thể nhàm chán nhưng rất cần.' },
  tenet: { en: 'a principle or belief', vi: 'nguyên tắc, tín điều', exEn: 'Fair assessment is a core tenet of IELTS.', exVi: 'Đánh giá công bằng là nguyên tắc cốt lõi của IELTS.' },
  trajectory: { en: 'the path of development', vi: 'quỹ đạo, hướng phát triển', exEn: 'Her score trajectory shows steady improvement.', exVi: 'Quỹ đạo điểm của cô ấy cho thấy tiến bộ đều.' },
  transcend: { en: 'to go beyond limits', vi: 'vượt qua, siêu việt', exEn: 'Great teachers transcend language barriers.', exVi: 'Giáo viên giỏi vượt qua rào cản ngôn ngữ.' },
  trivial: { en: 'of little importance', vi: 'tầm thường, không quan trọng', exEn: 'Do not waste time on trivial details in Task 1.', exVi: 'Đừng lãng phí thời gian vào chi tiết tầm thường ở Task 1.' },
  ubiquitous: { en: 'present everywhere', vi: 'phổ biến khắp nơi', exEn: 'Wi-Fi is ubiquitous on university campuses.', exVi: 'Wi-Fi phổ biến khắp khuôn viên đại học.' },
  unequivocal: { en: 'leaving no doubt; clear', vi: 'rõ ràng, không mơ hồ', exEn: 'The data provide unequivocal support for the theory.', exVi: 'Dữ liệu ủng hộ giả thuyết một cách rõ ràng.' },
  unilateral: { en: 'done by one party only', vi: 'một phía', exEn: 'Unilateral decisions may provoke opposition.', exVi: 'Quyết định một phía có thể gây phản đối.' },
  utilitarian: { en: 'designed to be useful rather than attractive', vi: 'thực dụng', exEn: 'The building has a utilitarian design.', exVi: 'Tòa nhà có thiết kế thực dụng.' },
  vacillate: { en: 'to waver between options', vi: 'dao động, lưỡng lự', exEn: 'Do not vacillate between two answers in the exam.', exVi: 'Đừng lưỡng lự giữa hai đáp án khi thi.' },
  vehement: { en: 'showing strong feeling', vi: 'mãnh liệt', exEn: 'She was vehement in defending her thesis.', exVi: 'Cô ấy bảo vệ luận điểm một cách mãnh liệt.' },
  venerable: { en: 'accorded great respect due to age', vi: 'đáng kính', exEn: 'The venerable institution celebrated its centenary.', exVi: 'Tổ chức đáng kính kỷ niệm 100 năm.' },
  verbose: { en: 'using more words than needed', vi: 'dài dòng', exEn: 'Verbose answers lose clarity and coherence.', exVi: 'Câu trả lời dài dòng mất rõ ràng và mạch lạc.' },
  vestige: { en: 'a trace of something disappearing', vi: 'dấu vết còn sót', exEn: 'Old customs are a vestige of colonial influence.', exVi: 'Phong tục cũ là dấu vết ảnh hưởng thuộc địa.' },
  vicarious: { en: 'experienced through another person', vi: 'gián tiếp, thay mặt', exEn: 'Parents feel vicarious pride in children\'s success.', exVi: 'Cha mẹ tự hào gián tiếp vì thành công con.' },
  vindicate: { en: 'to clear from blame; justify', vi: 'minh oan, chứng minh đúng', exEn: 'Results vindicated her study strategy.', exVi: 'Kết quả chứng minh chiến lược học của cô ấy đúng.' },
  virtuous: { en: 'having high moral standards', vi: 'đức hạnh', exEn: 'Virtuous leadership builds public trust.', exVi: 'Lãnh đạo đức hạnh xây dựng niềm tin công chúng.' },
  voracious: { en: 'wanting great quantities; eager', vi: 'ham đọc, tham lam', exEn: 'She is a voracious reader of academic journals.', exVi: 'Cô ấy ham đọc tạp chí học thuật.' },
  whimsical: { en: 'playfully quaint or unpredictable', vi: 'kỳ quặc, bất chợt', exEn: 'Whimsical ideas rarely suit formal essays.', exVi: 'Ý tưởng kỳ quặc hiếm phù hợp bài luận trang trọng.' },
  zealous: { en: 'showing great enthusiasm', vi: 'nhiệt huyết', exEn: 'Zealous preparation distinguishes top candidates.', exVi: 'Chuẩn bị nhiệt huyết tạo khác biệt cho ứng viên hàng đầu.' },
};